#!/bin/bash

ghci -v \
    -isrc:examples \
    -XOverloadedStrings -XTypeSynonymInstances -XFlexibleInstances \
    -XMultiParamTypeClasses -XGeneralizedNewtypeDeriving \
    -package bytestring-0.9.2.1 \
    "$@"
